-- SCORM 1.2 packages, their files, and learner tracking (F41).
--
-- ── WHY ──────────────────────────────────────────────────────────────────────
--
-- CLAUDE.md locks SCORM into v1 scope and nothing implemented it: no table,
-- no upload, no launch, no tracking. This is the storage for a minimal, real
-- SCORM 1.2 path (apps/web/src/lib/scorm/).
--
-- ── THE TABLES ───────────────────────────────────────────────────────────────
--
--   scorm_packages       one uploaded package, bound to an RTT subject
--                        (RESTRICT, like every RTT content key since 0031)
--                        and launched from that subject's page.
--   scorm_package_files  every file the upload validated, with the Storage
--                        key it was written to (bucket `scorm-packages`,
--                        _post/009). The content route serves a path only if
--                        it is a row here, so nothing an archive did not
--                        declare -- and nothing it declared unsafely -- can be
--                        served, and no object key is built from a name the
--                        archive chose.
--   scorm_attempts       the learner's SCORM record per package: status,
--                        score, location, suspend data, time. One row per
--                        (package, learner), because SCORM 1.2 resumes a
--                        single record on every launch.
--
-- The CHECKs are the SCORM 1.2 vocabularies (lesson_status, exit) and limits
-- (suspend_data is a CMIString4096; scores are 0-100): lib/scorm/cmi.ts
-- validates the same before a commit reaches the database.
--
-- Generated by drizzle-kit from schema/scorm.ts; the RLS lines at the end are
-- added by hand, for the reason 0037 gives.

CREATE TABLE "scorm_attempts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"package_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"lesson_status" varchar(16) DEFAULT 'not attempted' NOT NULL,
	"lesson_location" varchar(255) DEFAULT '' NOT NULL,
	"score_raw" real,
	"score_min" real,
	"score_max" real,
	"suspend_data" text DEFAULT '' NOT NULL,
	"exit" varchar(16) DEFAULT '' NOT NULL,
	"total_time_cs" bigint DEFAULT 0 NOT NULL,
	"session_time_cs" bigint DEFAULT 0 NOT NULL,
	"session_id" uuid,
	"session_seq" integer DEFAULT 0 NOT NULL,
	"session_count" integer DEFAULT 0 NOT NULL,
	"first_launched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "scorm_attempts_lesson_status_check" CHECK ("scorm_attempts"."lesson_status" IN ('passed', 'completed', 'failed', 'incomplete', 'browsed', 'not attempted')),
	CONSTRAINT "scorm_attempts_exit_check" CHECK ("scorm_attempts"."exit" IN ('time-out', 'suspend', 'logout', '')),
	CONSTRAINT "scorm_attempts_suspend_data_len" CHECK (length("scorm_attempts"."suspend_data") <= 4096),
	CONSTRAINT "scorm_attempts_score_range" CHECK (("scorm_attempts"."score_raw" IS NULL OR "scorm_attempts"."score_raw" BETWEEN 0 AND 100) AND ("scorm_attempts"."score_min" IS NULL OR "scorm_attempts"."score_min" BETWEEN 0 AND 100) AND ("scorm_attempts"."score_max" IS NULL OR "scorm_attempts"."score_max" BETWEEN 0 AND 100))
);
--> statement-breakpoint
CREATE TABLE "scorm_package_files" (
	"package_id" uuid NOT NULL,
	"path" text NOT NULL,
	"object_key" text NOT NULL,
	"size_bytes" integer NOT NULL,
	CONSTRAINT "scorm_package_files_package_id_path_pk" PRIMARY KEY("package_id","path")
);
--> statement-breakpoint
CREATE TABLE "scorm_packages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"rtt_subject_id" uuid NOT NULL,
	"title" varchar(240) NOT NULL,
	"manifest_identifier" text DEFAULT '' NOT NULL,
	"launch_path" text NOT NULL,
	"launch_query" text DEFAULT '' NOT NULL,
	"mastery_score" real,
	"launch_data" text,
	"file_count" integer NOT NULL,
	"total_bytes" bigint NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"uploaded_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "scorm_attempts" ADD CONSTRAINT "scorm_attempts_package_id_scorm_packages_id_fk" FOREIGN KEY ("package_id") REFERENCES "public"."scorm_packages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scorm_attempts" ADD CONSTRAINT "scorm_attempts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scorm_package_files" ADD CONSTRAINT "scorm_package_files_package_id_scorm_packages_id_fk" FOREIGN KEY ("package_id") REFERENCES "public"."scorm_packages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scorm_packages" ADD CONSTRAINT "scorm_packages_rtt_subject_id_rtt_subjects_id_fk" FOREIGN KEY ("rtt_subject_id") REFERENCES "public"."rtt_subjects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scorm_packages" ADD CONSTRAINT "scorm_packages_uploaded_by_user_id_users_id_fk" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "scorm_attempts_package_user_uq" ON "scorm_attempts" USING btree ("package_id","user_id");--> statement-breakpoint
CREATE INDEX "scorm_attempts_user_idx" ON "scorm_attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "scorm_packages_subject_idx" ON "scorm_packages" USING btree ("rtt_subject_id");--> statement-breakpoint

-- Closed to the Data API like every other table (see 0037): on an upgraded
-- database _post/002 has already run and never sees these tables, and
-- _post/always/001 only converges them after this migration has committed.
ALTER TABLE "scorm_packages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scorm_package_files" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scorm_attempts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

DO $$ BEGIN
  IF (SELECT count(*) = 2 FROM pg_roles WHERE rolname IN ('anon', 'authenticated')) THEN
    REVOKE ALL ON TABLE public.scorm_packages, public.scorm_package_files, public.scorm_attempts FROM anon, authenticated;
  END IF;
END $$;